apiVersion: v1
kind: Service
metadata:
  name:  {{ include "node-app.fullname" . }}
  labels: {{ include "node-app.labels" . | nindent 4 }}
spec:
  selector: {{ include "node-app.selectorLabels" . | nindent 4 }}
  ports:
  - name:  http
    port:  {{ .Values.service.port }} # service port. It will be used in ingress or gateway
    targetPort:  {{ .Values.container.port }} # container port of the pod. | Deployment.spec.template.spec.containers[].ports.containerPort